name: ChatOps Codemods

on:
  issue_comment:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  codemod:
    if: contains(github.event.comment.body, '/ui ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Parse command
        id: cmd
        run: |
          echo "CMD=$(echo "${{ github.event.comment.body }}" | tr -d '\r' | head -n1)" >> $GITHUB_OUTPUT
          echo "BR=chatops/$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Run codemod
        run: node .github/scripts/codemod.js "${{ steps.cmd.outputs.CMD }}"

      - name: Create branch if changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git switch -c "${{ steps.cmd.outputs.BR }}"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chatops: apply ${{ steps.cmd.outputs.CMD }}"
            git push --set-upstream origin "${{ steps.cmd.outputs.BR }}"
          else
            echo "No changes."
            exit 0
          fi

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.cmd.outputs.BR }}
          title: "ChatOps: ${{ steps.cmd.outputs.CMD }}"
          body: "Automatyczny PR z ChatOps."
          base: main
