name: ChatOps Codemods

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: write   # pozwala GITHUB_TOKEN robić commit

jobs:
  codemod:
    if: contains(github.event.comment.body, '/ui ') || contains(github.event.comment.body, '/menu ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse command
        id: parse
        run: echo "CMD<<EOF" >> $GITHUB_OUTPUT && echo "${{ github.event.comment.body }}" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Run codemod
        run: |
          node -v || sudo apt-get update && sudo apt-get install -y nodejs npm
          mkdir -p .github/scripts
          node .github/scripts/codemod.js "${{ steps.parse.outputs.CMD }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: chatops codemod -> ${{ steps.parse.outputs.CMD }}"
          branch: ${{ github.ref_name }}
